export type User = { id: number; name: string; email: string; roles: string[]; permissions: string[] }
export type Meta = { current_page: number; last_page: number; per_page: number; total: number }
export type ApiCollection<T> = { data: T[]; meta?: Meta }
export type ConsignorStockStatus = 'selling' | 'returned' | 'sold_out'
export type Consignor = { id: number; name: string; phone?: string; email?: string; address?: string; notes?: string; stock_status?: ConsignorStockStatus | null; is_active: boolean; products_count?: number; stock_count?: number; ready_count?: number; draft_count?: number; reserved_count?: number; sold_count?: number; payouts_count?: number; intake_batches_count?: number; can_delete?: boolean }
export type Lookup = { id: number; name: string }
export type ProductStatus = 'available' | 'pending' | 'reserved' | 'sold' | 'returned'
export type Product = { id: number; code: string; name: string | null; description?: string; purchase_price: number | null; selling_price: number | null; condition: string | null; status: ProductStatus; is_draft: boolean; intake_batch_id?: number; consignor?: Consignor; category?: Lookup; brand?: Lookup; customer?: Pick<Customer, 'id' | 'name' | 'phone'>; sold_at?: string; images?: { id: number; url: string; is_cover: boolean }[] }
export type Sale = { id: number; product: Product; customer_name: string; customer_phone?: string; sale_price: number; payment_method: string; sold_at: string }
export type PayoutItem = { sale_id: number; product_id: number; code: string; name: string; image?: string; category?: string; brand?: string; consignor_price: number; sale_price: number; profit?: number; customer_name: string; customer_phone?: string; payment_method?: string; sold_at: string }
export type Payout = { id: number; consignor: Consignor; amount: number; status: 'pending' | 'paid'; paid_at?: string; notes?: string; created_at?: string; items_count?: number; items?: PayoutItem[] }
export type OutstandingPayout = { consignor: Consignor; total_amount: number; total_sale_value: number; items_count: number; items: PayoutItem[] }
export type CustomerPurchase = { id: number; product: { id: number; code: string; name: string; category?: string; brand?: string; image?: string }; sale_price: number; payment_method: string; sold_at: string }
export type Customer = { id: number; name: string; phone?: string; notes?: string; purchases_count: number; total_spent: number; last_purchase_at?: string; purchases?: CustomerPurchase[]; created_at?: string }
export type OrderItem = { id: number; product_id: number; purchase_price?: number; sale_price?: number; completed_at?: string; product: Product }
export type Order = { id: number; code: string; status: 'pending' | 'paid' | 'cancelled'; payment_method?: string; total_amount: number; customer: Customer; items: OrderItem[]; paid_at?: string }
export type CheckoutItem = { id: number; product: { id: number; code: string; name: string; consignor?: string; image?: string }; sale_price: number }
export type Checkout = { id: string; code: string; customer: Pick<Customer, 'id' | 'name' | 'phone'>; items_count: number; total_amount: number; payment_method: string; paid_at: string; items: CheckoutItem[] }
export type Dashboard = { total_products: number; available_products: number; sold_products: number; total_consignors: number; monthly_revenue: number; monthly_profit: number; trend: { month: string; revenue: number; profit: number }[]; recent_sales: Sale[] }
